spring.application.name=Java5


# Kích thước tối đa mỗi file được tải lên
spring.servlet.multipart.max-file-size=10MB

# Kích thước tối đã của mỗi body request
# Tất cả các dữ liệu gửi lên khi submit form
# Text + File + ....
spring.servlet.multipart.max-request-size=500MB
