spring.application.name=Java5


# Kích thước tối đa mỗi file được tải lên
spring.servlet.multipart.max-file-size=10MB

# Kích thước tối đã của mỗi body request
# Tất cả các dữ liệu gửi lên khi submit form
# Text + File + ....
spring.servlet.multipart.max-request-size=500MB


spring.mvc.static-path-pattern=/images-upload/**
spring.web.resources.static-locations=file:images-upload/


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ecommerce_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456@Aa

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true